// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// wcov
Rcpp::List wcov(Eigen::MatrixXd& x, Eigen::VectorXd& w);
RcppExport SEXP _boRing_wcov(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(wcov(x, w));
    return rcpp_result_gen;
END_RCPP
}
// Mahalanobis
Eigen::MatrixXd Mahalanobis(Eigen::MatrixXd& x, Eigen::VectorXd& center, Eigen::MatrixXd& cov);
RcppExport SEXP _boRing_Mahalanobis(SEXP xSEXP, SEXP centerSEXP, SEXP covSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type center(centerSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type cov(covSEXP);
    rcpp_result_gen = Rcpp::wrap(Mahalanobis(x, center, cov));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_boRing_wcov", (DL_FUNC) &_boRing_wcov, 2},
    {"_boRing_Mahalanobis", (DL_FUNC) &_boRing_Mahalanobis, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_boRing(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
