# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name wcov
#' 
#' @title Weighted Covariance Matrix
#' 
#' @description \code{wcov} computes the estimates of the weighted covariance 
#'  matrix and the weighted mean of the data. 
#'
#' @param x A matrix with \eqn{m} columns and \eqn{n} rows, where each column 
#'  represents a different variable and each row a different observation. 
#'
#' @param w A non-negative and non-zero vector of weights for each observation. 
#'  Its length must equal the number of rows of x.
#'
#' @return A list with two components:
#'  \itemize{
#'   \item \code{center}: an estimate for the center (mean) of the data.
#'   \item \code{cov}: the estimated (weighted) covariance matrix.
#'  }
#'
#' @author Simon Garnier, \email{garnier@@njit.edu}
#'
#' @examples
#' m <- matrix(c(rnorm(500, 6), rnorm(500, 11, 3)), ncol = 2)
#' w <- runif(500)
#' wcov(m, w)
#'
wcov <- function(x, w) {
    .Call('_boRing_wcov', PACKAGE = 'boRing', x, w)
}

#' @name Mahalanobis
#' 
#' @title Mahalanobis Distance
#' 
#' @description \code{Mahalanobis} computes the squared Mahalanobis distance of
#'  all rows in \code{x} and the vector \eqn{\mu}{mu} = \code{center} with 
#'  respect to \eqn{\Sigma}{Sigma} = \code{cov}. This is (for vector \code{x}) 
#'  defined as \deqn{D^2 = (x - \mu)' \Sigma^{-1} (x - \mu)}{D^2 = (x - \mu)' 
#'  \Sigma^-1 (x - \mu)}
#'
#' @param x A matrix with \eqn{m} columns and \eqn{n} rows, where each column 
#'  represents a different variable and each row a different observation.
#'
#' @param center The mean vector of the distribution.
#'
#' @param cov The covariance matrix (\eqn{p \times p}{p x p}) of the 
#'  distribution.
#'
#' @return A matrix with 1 column and \eqn{n} rows reprensenting the estimated
#'  distance for each observation.
#'
#' @author Simon Garnier, \email{garnier@@njit.edu}
#'
#' @examples
#' m <- matrix(c(rnorm(500, 6), rnorm(500, 11, 3)), ncol = 2)
#' w <- runif(500)
#' covar <- wcov(m, w)
#' Mahalanobis(m, covar$center, covar$cov)
#'
Mahalanobis <- function(x, center, cov) {
    .Call('_boRing_Mahalanobis', PACKAGE = 'boRing', x, center, cov)
}

